keyboards:
  ergodox:
    layers:
      default:
        lights: []
        keys:
          left:
            - [esc, 1, 2, 3, 4, 5, ~]
            - [tab, q, w, e, r, t, ~]
            - [capsDance, a, s, d, f, g]
            - ['lShift', zDance, xDance, cDance, v, b, ~]
            - [~, ~, ~, left, right]
          left-thumb:
            - [esc, ~]
            - [home]
            - [space, backspace, end]
          right:
            - [~, 6, 7, 8, 9, 0, ~]
            - [~, y, u, i, o, p, \]
            - [   h, j, k, l, semicolonDance, quoteDance]
            - [~, n, m, commaDance, dotDance, slashDance, rShift]
            - ['[', ']', ~, ~, togglePlover]
          right-thumb:
            - [esc, ~]
            - [pageUp]
            - [pageDown, tab, enter]
      symbol:
        lights: [2]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, '!', '@', '{', '}', '/', ~]
            - [~, '#', '$', '(', ')', '`']
            - [~, '%', '^', '[', ']', '~', ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, delete, ~]
          right:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, '=', 7, 8, 9, '&', '|']
            - [   '+', 4, 5, 6, '*', ~]
            - [~, '-', 1, 2, 3, '/', ~, ~]
            - [~, ~, 0, '.', ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      navigation:
        lights: [1]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, mouseRightButton, mouseUp, mouseLeftButton, ~, ~]
            - [~, ~, mouseLeft, mouseDown, mouseRight, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
          right:
            - [~, shutdown, sleep, windowsMode, macosMode, ~, ~]
            - [~, ~, brightnessDown, brightnessUp, ~, ~, ~]
            - [   left, down, up, right, ~, ~]
            - [~, wheelLeft, wheelDown, wheelUp, wheelRight, ~, ~]
            - [      volumeDown, volumeUp, volumeToggle, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      emoji:
        lights: [1,3]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, 😊, 😂, 🤔, 👍, 💪, ~]
            - [~, 😏, 🔥, 💖, 😢, 😭]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
          right:
            - [enterBootloader, recordMacro1, recordMacro2, stopRecordMacro, playMacro1, playMacro2, ~]
            - [~, ~, F7Dance, F8Dance, F9Dance, ~, ~]
            - [   ~, F4Dance, F5Dance, F6Dance, ~, ~]
            - [~, ~, F1Dance, F2Dance, F3Dance, ~, ~]
            - [~, ~, F10Dance, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      plover:
        lights: [3]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
          right:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [   ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
  planck:
    layers:
      default:
        lights: []
        keys:
            - [tab, q, w, e, r, t, y, u, i, o, p, \]
            - [capsDance, a, s, d, f, g, h, j, k, l, semicolonDance, quoteDance]
            - [lShift, zDance, xDance, cDance, v, b, n, m, commaDance, dotDance, slashDance, rShift]
            - [~, ~, ~, space, backspace, space, tab, enter, '[', ']', togglePlover]
      symbol:
        lights: [1]
        keys:
            - [~, '!', '@', '{', '}','/', '=', 7, 8, 9, '&', '|']
            - [~, '#', '$', '(', ')', '`', '+', 4, 5, 6, '*', ~]
            - [~, '%', '^', '[', ']', '~', '-', 1, 2, 3, '/', ~]
            - [~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~]
      navigation:
        lights: [2]
        keys:
            - [~, ~, mouseRightButton, mouseUp, mouseLeftButton, ~, shutdown, sleep, windowsMode, macosMode, ~, ~]
            - [~, ~, mouseLeft, mouseDown, mouseRight, ~, left, down, up, right, ~, ~]
            - [~, ~, ~, ~, ~, ~, wheelLeft, wheelDown, wheelUp, wheelRight, ~, ~]
            - [~, ~, ~, ~, ~, ~, volumeDown, volumeUp, volumeToggle, ~, ~]
      emoji:
        lights: [1,2]
        keys:
            - [~, 😊, 😂, 🤔, 👍, 💪, ~, F7Dance, F8Dance, F9Dance, ~, ~]
            - [~, 😏, 🔥, 💖, 😢, 😭, ~, F4Dance, F5Dance, F6Dance, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, F1Dance, F2Dance, F3Dance, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, F10Dance, ~, ~, ~]
      plover:
        lights: [2]
        keys:
            - [~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, ~, ~, ~, ~]

keys:
  capsDance:
    type: dance
    tap:
    - [capsLock]
    - [toggleSymbol]
    hold:
    - [holdSymbol]
    - [holdSymbol, lctrl]
    - [holdSymbol, lalt]
  zDance:
    type: dance
    tap: 
    - [z]
    hold:
    - [lctrl]
    - [lctrl, lShift]
    - [lctrl, lShift, lalt]
  xDance:
    type: dance
    tap: 
    - [x]
    hold:
    - [lalt]
    - [lalt, lShift]
    - [lalt, lShift, lctrl]
  cDance:
    type: dance
    tap: 
    - [c]
    hold:
    - [lgui]
    - [lgui, lShift]
    - [lgui, lShift, lctrl]
  slashDance:
    type: dance
    tap: 
    - ['/']
    hold:
    - [rctrl]
    - [rctrl, rShift]
    - [rctrl, rShift, ralt]
  dotDance:
    type: dance
    tap: 
    - ['.']
    hold:
    - [ralt]
    - [ralt, rShift]
    - [ralt, rShift, rctrl]
  commaDance:
    type: dance
    tap: 
    - [',']
    hold:
    - [rgui]
    - [rgui, rShift]
    - [rgui, rShift, rctrl]
  F1Dance: { type: dance, tap: [['f1'], ['f11']]}
  F2Dance: { type: dance, tap: [['f2'], ['f12']]}
  F3Dance: { type: dance, tap: [['f3'], ['f13']]}
  F4Dance: { type: dance, tap: [['f4'], ['f14']]}
  F5Dance: { type: dance, tap: [['f5'], ['f15']]}
  F6Dance: { type: dance, tap: [['f6'], ['f16']]}
  F7Dance: { type: dance, tap: [['f7'], ['f17']]}
  F8Dance: { type: dance, tap: [['f8'], ['f18']]}
  F9Dance: { type: dance, tap: [['f9'], ['f19']]}
  F10Dance: { type: dance, tap: [['f10'], ['f20']]}
  semicolonDance:
    type: dance
    tap:
    - [';']
    hold:
    - [holdNavigation]
  quoteDance:
    type: dance
    tap:
    - ["'"]
    hold:
    - [holdEmoji]
    - [holdEmoji, lctrl]
    - [holdEmoji, lctrl, lalt]
map:
    'shift(': LSPO
    'shift)': RSPC
    pageUp: PGUP
    pageDown: PGDN
    space: SPC
    backspace: BSPC
    enter: ENT
    '[': LBRC 
    ']': RBRC 
    '(': LPRN
    ')': RPRN
    '{': LCBR
    '}': RCBR
    "'": QUOT
    ',': COMM
    '`': GRV
    .: DOT
    '\': BSLS
    /: SLSH
    '!': EXLM
    '@': AT
    '#': HASH
    '$': DLR
    '%': PERC
    '~': TILD
    '^': CIRC
    '+': PPLS
    '-': MINS
    '*': PAST
    '=': EQL
    '&': AMPR
    '|': PIPE
    ';': SCOLON
    mouseLeftButton: BTN1
    mouseRightButton: BTN2
    mouseLeft: MS_L
    mouseRight: MS_R
    mouseUp: MS_U
    mouseDown: MS_D
    wheelLeft: WH_L
    wheelRight: WH_R
    wheelUp: WH_U
    wheelDown: WH_D
    left: LEFT
    right: RGHT
    up: UP
    down: DOWN
    brightnessUp: BRIU
    brightnessDown: BRID
    volumeUp: VOLU
    volumeDown: VOLD
    volumeToggle: MUTE
    shutdown: PWR
    sleep: SLEP
    windowsMode: UC_M_WC
    macosMode: UC_M_OS
    playMacro1: DYN_MACRO_PLAY1
    playMacro2: DYN_MACRO_PLAY2
    recordMacro1: DYN_REC_START1
    recordMacro2: DYN_REC_START2
    stopRecordMacro: DYN_REC_STOP
    enterBootloader: ZKC_BTL