keyboards:
  ergodox:
    layers:
      default:
        keys:
          left:
            - [esc, 1, 2, 3, 4, 5, ~]
            - [tab, q, w, e, r, t, ~]
            - [capsDance, a, s, d, f, g]
            - ["shift(", zDance, x, c, v, b, ~]
            - [~, ~, ~, left, right]
            - [esc, ~]
            - [home]
            - [space, backspace, end]
          right:
            - [~, 6, 7, 8, 9, 0, ~]
            - [~, y, u, i, o, p, \]
            - [h, j, k, l, semicolonDance, "'"]
            - [~, n, m, ",", ".", "/", "shift)"]
            - ["[", "]", \, "`", togglePlover]
            - [esc, ~]
            - [pageUp]
            - [pageDown, tab, enter]
keys:
  capsDance:
    type: dance
    tap:
    - [capsLock]
    - [toggleSymbol]
    hold:
    - [holdSymbol]
    - [holdSymbol, ctrl]
    - [holdSymbol, alt]
  zDance:
    type: dance
    tap: 
    - [z]
    hold:
    - [ctrl]
    - [ctrl, shift]
    - [ctrl, shift, alt]
  semicolonDance:
    type: dance
    tap:
    - [semicolon]
    hold:
    - [holdNavigation]
    - [holdSymbol]
map:
    "shift(": LSPO
    "shift)": RSPO
    "[": LBRC 
    "]": RBRC 
    "'": QUOT
    ",": COMM
    "`": GRV
    .: DOT
    \: BSL
    pageUp: PGUP
    pageDown: PGUP
    space: SPC
    backspace: BSPC