name: release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # docker
    - uses: docker/setup-buildx-action@v1.1.1
      id: buildx
      with:
        install: true
    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-

    # git
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: vendor/qmk_firmware
        key: ${{ runner.os }}-gitmodules-1-${{ hashFiles('**/.gitmodules') }}
        restore-keys: ${{ runner.os }}-gitmodules-1-

    - run: ./project.sh sync
    - run: ./project.sh build-all
    - uses: softprops/action-gh-release@v1
      if: "startsWith(github.ref, 'refs/tags/v')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          firmwares/ergodox_ez.hex
          firmwares/planck.bin
          firmwares/ymd09.hex
    - run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache